### ISSUE TITLE
Installing via. Composer

### ISSUE THREAD

**Issue by danken00** [MWDelaney/bootstrap-3-shortcodes#129]
Hey, I must be doing something wrong here; I can't figure out how to install this via. Composer. What would be the command (or how would I edit my `composer.json` file) to get this to install?

I've tried the usual:

    composer require filipstefansson/bootstrap-3-shortcodes
    composer require filipstefansson/bootstrap-3-shortcodes:3.3.6

But Composer says the package is not available :(

**Comment by t-richards** [comment]
@danken00 

I'd recommend using the [WordPress Packagist Composer Repository](http://wpackagist.org/). Once you add the repo to your `composer.json`:

```json
"repositories": [
    {
        "type":"composer",
        "url":"http://wpackagist.org"
    }
],
```

...locate your desired plugin: http://wpackagist.org/search?q=bootstrap-3-shortcodes and then require it:

```bash
$ composer require wpackagist-plugin/bootstrap-3-shortcodes
```

Alternatively, you could manually add this one specific plugin as a "VCS repository": https://getcomposer.org/doc/05-repositories.md#vcs

**Comment by MWDelaney** [comment]
wpackagist is the best way to include this plugin via composer. Closing this issue.
