### ISSUE TITLE
container-fluid as distinct shortcode

### ISSUE THREAD

**Issue by gstreetmedia** [MWDelaney/bootstrap-3-shortcodes#130]
Due to the fact that you cannot nest a shortcode of the same name, i recommend that "container-fluid' have its own short code. This allows for a container-fluid to have a nested container, whic is very useful if you want a "row/section" with a different background color or distinct background image. 

For example, the following will not currently work in WordPress

[container fluid='true' style='background:#FAFAFA']
[container]
....content here
[/container]
[/container]

However, with a 'container-fluid' short code, you can do this

[container-fluid style='background:#FAFAFA']
[container]
....content here
[/container]
[/container-fluid]

I made a custom version that does this. Took me about five minutes. Would be happy to submit a PR.

**Comment by MWDelaney** [comment]
Hi, I'd love to see a PR on this. Thank you and sorry for the delay!
