### ISSUE TITLE
Transfer repo ownership

### ISSUE THREAD

**Issue by MWDelaney** [MWDelaney/bootstrap-3-shortcodes#133]
Hey @filipstefansson would you be willing to transfer ownership of this repo to me? No big deal if not. Thanks!

**Comment by filipstefansson** [comment]
No problem, but you need to delete the fork you have before I can transfer it!

**Comment by MWDelaney** [comment]
Done! I didn't even realize I had that fork anymore.

**Comment by MWDelaney** [comment]
Is it still not working?

**Comment by filipstefansson** [comment]
I think you have to accept it somehow: 
![image](https://www.dropbox.com/s/ad0tstbytxulnig/Screenshot%202016-05-03%2021.35.50.png?dl=1)

**Comment by MWDelaney** [comment]
I think my email notification were sending to the wrong place. Can you abort and re-try?

**Comment by filipstefansson** [comment]
I tried again now!
