### ISSUE TITLE
Bootstrap 4 support

### ISSUE THREAD

**Issue by LittleHamster** [MWDelaney/bootstrap-3-shortcodes#139]
Hello, 
any possible update whether this plugin is going to support Bootstrap 4? Alpha 5 was released almost a month ago, soon the 6 is going to be released and then the final version.

any ideas?

**Comment by MWDelaney** [comment]
This plugin won't be updated to support Bootstrap 4, but there is a very-much-work-in-progress, definitely-not ready-for-production-use plugin for Bootstrap 4 [here](https://github.com/MWDelaney/bootstrap-4-shortcodes). The philosophy behind this update is a little different, and we probably won't be supporting migration from this plugin to that, but you can keep an eye on that plugin's development.
