### ISSUE TITLE
A few UI suggestions

### ISSUE THREAD

**Issue by LittleHamster** [MWDelaney/bootstrap-3-shortcodes#140]
This is one of the best plugins for bootstrap, well done guys 👍 
just a few suggestions I wanted to make: 

**Improve the visual elements:** 
right now when you click on the icon in the editor, you see a long list of elements. 
maybe implement it like the Site Builder plugin: 

![screenshot-2](https://cloud.githubusercontent.com/assets/10330481/20424335/508f5e66-ad43-11e6-8f70-ac34b8afaee7.png)

so the left tabs would be: CSS / Components / JavaScript and their corresponding elements on the right

**Allow data insertion within the elements**
right now the only way to insert the shortcode is to insert an example. What if you allow user to enter their data?

maybe like this: 
![screenshot-6](https://cloud.githubusercontent.com/assets/10330481/20424470/0d8111c2-ad44-11e6-8ed8-041ad261c407.png)

**Comment by MWDelaney** [comment]
These are some good suggestions but right now they fall outside the scope of this plugin. we would definitely look at a pull request, but these encancements aren't what we're focusing on right now.

**Comment by LittleHamster** [comment]
@MWDelaney okay, thanks. Can you leave this issue open and label it as "improvement" or something similar so if other people want to contribute ? thanks
