### ISSUE TITLE
Uncaught TypeError: 

### ISSUE THREAD

**Issue by KevinBatdorf** [MWDelaney/bootstrap-3-shortcodes#144]
`Uncaught TypeError: jQuery(...).removeAttr(...).nextUntil(...).andSelf is not a function`

Happens on custom admin pages. It's from this code:

```javascript
jQuery('#bootstrap-shortcodes-help h2').each(function(){
    var id = jQuery(this).attr("id");
    jQuery(this).removeAttr("id").nextUntil("h2").andSelf().wrapAll('<div class="tab-pane" id="bs-' + id + '" />');
});
```

**Comment by MWDelaney** [comment]
Replying a year later. Better late than never? Probably to? 

If you're using a non-WordPress-default version of jQuery for your site you could run into this error, as `andSelf()` is deprecated in newer versions.

**Comment by audioscavenger** [comment]
just replace andSelf by addBack that's it.
andSelf() function has been deprecated and is now an alias for .addBack(), which should be used with jQuery 1.8 and later.
