### ISSUE TITLE
Nested columns not working

### ISSUE THREAD

**Issue by aidan2129** [MWDelaney/bootstrap-3-shortcodes#146]
I am trying to add code similar to the example on the bootstrap [docs here](https://getbootstrap.com/docs/3.3/css/#grid-nesting) but the short code is not formatting when nested items are added. The last close tags are just being rendered as Text example below.
```
[row]
  [column sm="9"]
    Level 1: .col-sm-9
       [row]
              [column sm="6" xs="8" ]
                Level 2: .col-xs-8 .col-sm-6
              [/column]
              [column sm="6" xs="8" ]
                Level 2: .col-xs-4 .col-sm-6
              [/column]
        [/row]
  [/column]
[/row]
```
On the frontend the closing shortcode is rendered:

Level 1: .col-sm-9     Level 2: .col-xs-8 .col-sm-6
Level 2: .col-xs-4 .col-sm-6
[/column]
[/row]

**Comment by MWDelaney** [comment]
As discussed in #46, #63, and #86, WordPress doesn't allow nested shortcodes of the same name (see WordPress documentation here: https://codex.wordpress.org/Shortcode_API#Nested_Shortcodes). We've looked into supporting this (as noted in #86) but any solution we've found ultimately creates more clutter, and more documentation issues than we're prepared to deal with right now.
