### ISSUE TITLE
Adding icon to collapsible

### ISSUE THREAD

**Issue by chopinesque** [MWDelaney/bootstrap-3-shortcodes#150]
Hi and thank you for this great plugin!

I am trying to use a collapsible like this but I cannot find how to add a plus icon at the right that would appear on active state and a minus one on non-active.

```
[collapse title="Title" active="false" type="info"]
...
[/collapse]
```

**Comment by MWDelaney** [comment]
Hi,
Since `+` and `-` icons aren't part of the default look of accordions for Bootstrap (see [here](https://getbootstrap.com/docs/3.3/javascript/#collapse-example-accordion)), this plugin doesn't support adding them.

You could add `+` and `-` icons pretty easily in your stylesheet.
