### ISSUE TITLE
Support for WP v.4.9

### ISSUE THREAD

**Issue by kkampardi** [MWDelaney/bootstrap-3-shortcodes#151]
This is a very useful plugin for Wordpress
Is this going to get tested for >v.4.6.9?

Thanks!

**Comment by patrikalienus** [comment]
I have a feeling the author is not maintaining this at all.

**Comment by MWDelaney** [comment]
Hi, thanks for bugging me about this. I tested on 4.9 and pushed a new version with updated supported versions.
