### ISSUE TITLE
tooltip not working: "not a function" message.

### ISSUE THREAD

**Issue by feralreason** [MWDelaney/bootstrap-3-shortcodes#77]
Tooltip, using this shortcode, is not working:

[tooltip title="I'm the title" placement="left"]Hmmm, Tooltip[/tooltip]

I get the following error in the Firebug console:

TypeError: $(...).tooltip is not a function
$('.bs-tooltip').tooltip();

Which references line 2 of bootstrap-shorcodes-tooltip.js:

(function($) {
      $('.bs-tooltip').tooltip();
})(jQuery);

(I am loading .../bootstrap/dist/js/bootstrap.min.js in the header of my theme, and all other shortcodes I have tested seem to work except this one and popover, which fails with a similar Firebug notice.)

**Comment by C0ZEN** [comment]
Old topic however I've got the same problem.

I used nodejs, angular, npm, yeoman, grunt, bower, etc...
Bower handle bootstrap (added with yo) when building.

I've got the line in the .js build : 

    <script src="bower_components/bootstrap/dist/js/bootstrap.js"></script>
At the end of my index.html, I added this code : 

    $(document).ready(function(){
        $('[data-hover="tooltip"]').tooltip( {
          delay: {show: 500, hide: 100},
          container: 'body'
        });
    });
The error is in the title of this thread, it's the same !
It's not logic (the function is present in the file).
So I juste add this line to get the job done : 

    <script src="../bower_components/bootstrap/js/tooltip.js" type="text/javascript"></script>

**Comment by beno** [comment]
First install, bootstrap working correctly 100%, and I run into this. Ah, Summernote, you looked so promising.

**Comment by MWDelaney** [comment]
@beno can you tell us more about what you're trying to do? Are you working with a theme that might be conflicting with this plugin? 

I would like to help troubleshoot this issue. If there's a problem with this plugin I want to fix it!

**Comment by beno** [comment]
Never mind, I was in the wrong thread. Sorry.
